## Deliverable 2. Create a Customer Travel Destinations Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [2]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("../Weather_Database/WeatherPy_database.csv")
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current description
0,0,Luderitz,NaN,-26.6481,15.1594,77.56,47,0,29.62,clear sky
1,1,Comodoro Rivadavia,AR,-45.8667,-67.5000,71.60,60,75,4.61,broken clouds
2,2,Grindavik,IS,63.8424,-22.4338,30.20,86,75,26.46,broken clouds
3,3,Santa Catalina,PH,9.3337,122.8637,80.60,83,75,6.91,broken clouds
4,4,Saint-Medard-En-Jalles,FR,44.8969,-0.7214,57.00,58,0,5.75,clear sky

In [3]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 60
What is the maximum temperature you would like for your trip? 90

In [4]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current description
0,0,Luderitz,NaN,-26.6481,15.1594,77.56,47,0,29.62,clear sky
1,1,Comodoro Rivadavia,AR,-45.8667,-67.5000,71.60,60,75,4.61,broken clouds
3,3,Santa Catalina,PH,9.3337,122.8637,80.60,83,75,6.91,broken clouds
5,5,Pastos Bons,BR,-6.6017,-44.0767,79.21,80,100,5.17,overcast clouds
6,6,Hermanus,ZA,-34.4187,19.2345,75.99,57,24,8.01,few clouds
13,13,Yeppoon,AU,-23.1333,150.7333,78.80,73,39,5.73,scattered clouds
16,16,Busselton,AU,-33.6500,115.3333,69.94,81,0,6.62,clear sky
17,17,Kapaa,US,22.0752,-159.3190,69.80,83,90,29.93,light rain
19,19,Serra Talhada,BR,-7.9919,-38.2983,85.06,41,77,9.60,broken clouds
23,23,Butaritari,KI,3.0707,172.7902,80.76,83,100,18.01,light rain

In [5]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.count()

City_ID                317
City                   317
Country                313
Lat                    317
Lng                    317
Max Temp               317
Humidity               317
Cloudiness             317
Wind Speed             317
Current description    317
dtype: int64

In [6]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
preferred_cities_df.dropna(inplace=True)
preferred_cities_df.count()

C:\Users\johnj\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

City_ID                313
City                   313
Country                313
Lat                    313
Lng                    313
Max Temp               313
Humidity               313
Cloudiness             313
Wind Speed             313
Current description    313
dtype: int64

In [11]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Current description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.count()

City                   313
Country                313
Max Temp               313
Current description    313
Lat                    313
Lng                    313
Hotel Name             313
dtype: int64

In [15]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    params["location"] = f"{lat},{lng}"

    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()

    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

hotel_df.head()

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

,City,Country,Max Temp,Current description,Lat,Lng,Hotel Name
1,Comodoro Rivadavia,AR,71.60,broken clouds,-45.8667,-67.5000,Austral Hotel
3,Santa Catalina,PH,80.60,broken clouds,9.3337,122.8637,Don Pacondo
5,Pastos Bons,BR,79.21,overcast clouds,-6.6017,-44.0767,Área de lazer casa (Pucina)
6,Hermanus,ZA,75.99,few clouds,-34.4187,19.2345,Misty Waves Boutique Hotel
13,Yeppoon,AU,78.80,scattered clouds,-23.1333,150.7333,Villa Mar Colina

In [19]:
# 7. Drop the rows where there is no Hotel Name.
hotel_df.dropna(inplace=True)
hotel_df.head(50)

,City,Country,Max Temp,Current description,Lat,Lng,Hotel Name
1,Comodoro Rivadavia,AR,71.60,broken clouds,-45.8667,-67.5000,Austral Hotel
3,Santa Catalina,PH,80.60,broken clouds,9.3337,122.8637,Don Pacondo
5,Pastos Bons,BR,79.21,overcast clouds,-6.6017,-44.0767,Área de lazer casa (Pucina)
6,Hermanus,ZA,75.99,few clouds,-34.4187,19.2345,Misty Waves Boutique Hotel
13,Yeppoon,AU,78.80,scattered clouds,-23.1333,150.7333,Villa Mar Colina
16,Busselton,AU,69.94,clear sky,-33.6500,115.3333,Observatory Guest House
17,Kapaa,US,69.80,light rain,22.0752,-159.3190,Sheraton Kauai Resort at Coconut Beach
19,Serra Talhada,BR,85.06,broken clouds,-7.9919,-38.2983,Pousada São Luiz
23,Butaritari,KI,80.76,light rain,3.0707,172.7902,Isles Sunset Lodge
24,Bredasdorp,ZA,77.00,scattered clouds,-34.5322,20.0403,Bredasdorp Country Manor
27,Port Hedland,AU,89.60,broken clouds,-20.3167,118.5667,The Esplanade Hotel
28,Ambon,ID,80.60,scattered clouds,-3.6954,128.1814,Swiss-Belhotel Ambon
30,Rikitea,PF,77.47,broken clouds,-23.1203,-134.9692,Pension Maro'i
33,Kruisfontein,ZA,78.01,broken clouds,-34.0033,24.7314,Oyster Bay House Rental
34,Kendari,ID,77.59,overcast clouds,-3.9450,122.4989,Hotel Wixel
36,Luanda,AO,82.40,broken clouds,-8.8368,13.2343,EPIC SANA Luanda
38,Cabedelo,BR,82.40,broken clouds,-6.9811,-34.8339,Hotel Pigalle
39,Castro,BR,64.11,light rain,-24.7911,-50.0119,CHACARA BAILLY
40,Victoria,HK,62.01,broken clouds,22.2855,114.1577,Mini Hotel Central
43,Puerto Ayora,EC,73.00,broken clouds,-0.7393,-90.3518,Castillo Galapagos
47,Champerico,GT,71.60,clear sky,14.3000,-91.9167,"Hotel y restaurante ""El Diamante"""
52,Cabo San Lucas,MX,66.99,clear sky,22.8909,-109.9124,Hotel Tesoro Los Cabos
53,Waddan,LY,60.03,clear sky,29.1614,16.1390,محل الشريف محمد العايب
54,Dingle,PH,73.27,light rain,10.9995,122.6711,SEGAYA PROPERTY
56,Faanui,PF,81.00,clear sky,-16.4833,-151.7500,Bora-Bora Pearl Beach Resort & Spa
57,Kerman,IR,62.60,clear sky,30.2832,57.0788,هتل آپارتمان آسام
58,Vaini,TO,77.00,few clouds,-21.2000,-175.2000,Keleti Beach Resort
60,Ponta Do Sol,PT,66.20,scattered clouds,32.6667,-17.1000,Hotel do Campo
61,San Cristobal,VE,77.00,light rain,7.7669,-72.2250,Pirineos
62,Ugoofaaru,MV,81.88,clear sky,5.6667,73.0000,Ungoofaaru Inn
63,Villarrica,PY,75.99,few clouds,-25.7500,-56.4333,Mansión Reljuv Tours SA
64,Cape Town,ZA,77.00,few clouds,-33.9258,18.4232,"Radisson Blu Hotel Waterfront, Cape Town"
70,Mar Del Plata,AR,75.20,clear sky,-38.0023,-57.5575,Gran Hotel Mar del Plata
71,Acari,PE,75.31,broken clouds,-15.4311,-74.6158,HOSPEDAJE XIMENA
72,Beeville,US,68.00,overcast clouds,28.4008,-97.7483,Holiday Inn Express & Suites Beeville
74,Singkang,MY,78.80,few clouds,2.1006,102.7994,Kampung Seri Makmor Pagoh
75,Plettenberg Bay,ZA,70.79,overcast clouds,-34.0527,23.3716,Thanda Vista B&B
78,Seoni,IN,73.69,clear sky,22.0833,79.5333,STARiHOTELS Nehru Road Seoni
79,Vila Franca Do Campo,PT,62.01,few clouds,37.7167,-25.4333,Pestana Bahia Praia
80,Hithadhoo,MV,81.52,overcast clouds,-0.6000,73.0833,Scoop Guest House
81,Avarua,CK,82.40,few clouds,-21.2078,-159.7750,Paradise Inn
82,Esperance,AU,80.60,clear sky,-33.8667,121.9000,Hospitality Esperance
85,Port Alfred,ZA,75.00,clear sky,-33.5906,26.8910,The Halyards Hotel
86,Harper,LR,84.04,light rain,4.3750,-7.7169,Screensaver
90,Pochutla,MX,68.00,broken clouds,15.7432,-96.4661,Hotel Posada San Jose
91,Atuona,PF,77.72,clear sky,-9.8000,-139.0333,Villa Enata
92,Souillac,MU,86.00,light rain,-20.5167,57.5167,Shanti Maurice Resort & Spa
94,Knysna,ZA,68.00,overcast clouds,-34.0363,23.0471,Protea Hotel by Marriott Knysna Quays
95,Carnarvon,AU,78.80,clear sky,-24.8667,113.6333,Hospitality Carnarvon
96,Saint-Philippe,RE,89.60,broken clouds,-21.3585,55.7679,"Chambres d'hôte ""La Trinité"""

In [23]:
# 8a. Create the output File (CSV)
output_data_file = "WeatherPy_Vacation.csv"
# 8b. Export the City_Data into a csv
hotel_df.to_csv(output_data_file, index_label="City_ID")

In [26]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
<dt>Weather Description</dt><dd>{Current description}</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = hotel_df[["Lat", "Lng"]]

In [27]:
# 11a. Add a marker layer for each city to the map. 
# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))